version = 0.1

[default.deploy.parameters]
stack_name = "taxflowai-backend"
resolve_s3 = true
s3_prefix = "taxflowai-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
